#! /usr/bin/env python
# -*- encoding: utf-8 -*-

import json

old_moves = {
"Thunder Shock" : "Éclair",
"Quick Attack" : "Vive-Attaque",
"Scratch" : "Griffe",
"Ember" : "Flammèche",
"Vine Whip" : "Fouet Lianes",
"Tackle" : "Charge",
"Razor Leaf" : "Tranch’Herbe",
"Take Down" : "Bélier",
"Water Gun" : "Pistolet à O",
"Bite" : "Morsure",
"Pound" : "Écras’Face",
"Double Slap" : "Torgnoles",
"Wrap" : "Ligotage",
"Hyper Beam" : "Ultralaser",
"Lick" : "Léchouille",
"Dark Pulse" : "Vibrobscur",
"Smog" : "Purédpois",
"Sludge" : "Détritus",
"Metal Claw" : "Griffe Acier",
"Vice Grip" : "Force Poigne",
"Flame Wheel" : "Roue de Feu",
"Megahorn" : "Mégacorne",
"Wing Attack" : "Cru-Aile",
"Flamethrower" : "Lance-Flammes",
"Sucker Punch" : "Coup Bas",
"Dig" : "Tunnel",
"Low Kick" : "Balayage",
"Cross Chop" : "Coup-Croix",
"Psycho Cut" : "Coupe Psycho",
"Psybeam" : "Rafale Psy",
"Earthquake" : "Séisme",
"Stone Edge" : "Lame de Roc",
"Ice Punch" : "Poing-Glace",
"Heart Stamp" : "Crève-Cœur",
"Discharge" : "Coup d’Jus",
"Flash Cannon" : "Luminocanon",
"Peck" : "Picpic",
"Drill Peck" : "Bec Vrille",
"Ice Beam" : "Laser Glace",
"Blizzard" : "Blizzard",
"Air Slash" : "Lame d’Air",
"Heat Wave" : "Canicule",
"Twineedle" : "Double-Dard",
"Poison Jab" : "Direct Toxik",
"Aerial Ace" : "Aéropique",
"Drill Run" : "Tunnelier",
"Petal Blizzard" : "Tempête Florale",
"Mega Drain" : "Méga-Sangsue",
"Bug Buzz" : "Bourdon",
"Poison Fang" : "Crochet Venin",
"Night Slash" : "Tranche-Nuit",
"Slash" : "Tranche",
"Bubble Beam" : "Bulles d’O",
"Submission" : "Sacrifice",
"Karate Chop" : "Poing-Karaté",
"Low Sweep" : "Balayette",
"Aqua Jet" : "Aqua-Jet",
"Aqua Tail" : "Hydroqueue",
"Seed Bomb" : "Canon Graine",
"Psyshock" : "Choc Psy",
"Rock Throw" : "Jet-Pierres",
"Ancient Power" : "Pouvoir Antique",
"Rock Tomb" : "Tomberoche",
"Rock Slide" : "Éboulement",
"Power Gem" : "Rayon Gemme",
"Shadow Sneak" : "Ombre Portée",
"Shadow Punch" : "Poing Ombre",
"Shadow Claw" : "Griffe Ombre",
"Ominous Wind" : "Vent Mauvais",
"Shadow Ball" : "Ball’Ombre",
"Bullet Punch" : "Pisto-Poing",
"Magnet Bomb" : "Bombaimant",
"Steel Wing" : "Aile d’Acier",
"Iron Head" : "Tête de Fer",
"Parabolic Charge" : "Parabocharge",
"Spark" : "Étincelle",
"Thunder Punch" : "Poing-Éclair",
"Thunder" : "Fatal-Foudre",
"Thunderbolt" : "Tonnerre",
"Twister" : "Ouragan",
"Dragon Breath" : "Dracosouffle",
"Dragon Pulse" : "Dracochoc",
"Dragon Claw" : "Dracogriffe",
"Disarming Voice" : "Voix Enjôleuse",
"Draining Kiss" : "Vampibaiser",
"Dazzling Gleam" : "Éclat Magique",
"Moonblast" : "Pouvoir Lunaire",
"Play Rough" : "Câlinerie",
"Cross Poison" : "Poison-Croix",
"Sludge Bomb" : "Bomb-Beurk",
"Sludge Wave" : "Cradovague",
"Gunk Shot" : "Détricanon",
"Mud Shot" : "Tir de Boue",
"Bone Club" : "Massd’Os",
"Bulldoze" : "Piétisol",
"Mud Bomb" : "Boue-Bombe",
"Fury Cutter" : "Taillade",
"Bug Bite" : "Piqûre",
"Signal Beam" : "Rayon Signal",
"X-Scissor" : "Plaie-Croix",
"Flame Charge" : "Nitrocharge",
"Flame Burst" : "Rebondifeu",
"Fire Blast" : "Déflagration",
"Brine" : "Saumure",
"Water Pulse" : "Vibraqua",
"Scald" : "Ébullition",
"Hydro Pump" : "Hydrocanon",
"Psychic" : "Psyko",
"Psystrike" : "Frappe Psy",
"Ice Shard" : "Éclats Glace",
"Icy Wind" : "Vent Glace",
"Frost Breath" : "Souffle Glacé",
"Absorb" : "Vol-Vie",
"Giga Drain" : "Giga-Sangsue",
"Fire Punch" : "Poing de Feu",
"Solar Beam" : "Lance-Soleil",
"Leaf Blade" : "Lame-Feuille",
"Power Whip" : "Mégafouet",
"Splash" : "Trempette",
"Acid" : "Acide",
"Air Cutter" : "Tranch’Air",
"Hurricane" : "Vent Violent",
"Brick Break" : "Casse-Brique",
"Cut" : "Coupe",
"Swift" : "Météores",
"Horn Attack" : "Koud’Korne",
"Stomp" : "Écrasement",
"Headbutt" : "Coup d’Boule",
"Hyper Fang" : "Croc de Mort",
"Slam" : "Souplesse",
"Body Slam" : "Plaquage",
"Rest" : "Repos",
"Struggle" : "Lutte",
"Scald" : "Ébullition",
"Hydro Pump" : "Hydrocanon",
"Wrap" : "Ligotage",
"Wrap" : "Ligotage",
"Fury Cutter" : "Taillade",
"Bug Bite" : "Piqûre",
"Bite" : "Morsure",
"Sucker Punch" : "Coup Bas",
"Dragon Breath" : "Dracosouffle",
"Thunder Shock" : "Éclair",
"Spark" : "Étincelle",
"Low Kick" : "Balayage",
"Karate Chop" : "Poing-Karaté",
"Ember" : "Flammèche",
"Wing Attack" : "Cru-Aile",
"Peck" : "Picpic",
"Lick" : "Léchouille",
"Shadow Claw" : "Griffe Ombre",
"Vine Whip" : "Fouet Lianes",
"Razor Leaf" : "Tranch’Herbe",
"Mud Shot" : "Tir de Boue",
"Ice Shard" : "Éclats Glace",
"Frost Breath" : "Souffle Glacé",
"Quick Attack" : "Vive-Attaque",
"Scratch" : "Griffe",
"Tackle" : "Charge",
"Pound" : "Écras’Face",
"Cut" : "Coupe",
"Poison Jab" : "Direct Toxik",
"Acid" : "Acide",
"Psycho Cut" : "Coupe Psycho",
"Rock Throw" : "Jet-Pierres",
"Metal Claw" : "Griffe Acier",
"Bullet Punch" : "Pisto-Poing",
"Water Gun" : "Pistolet à O",
"Splash" : "Trempette",
"Water Gun" : "Pistolet à O",
"Mud-Slap" : "Coud’Boue",
"Zen Headbutt" : "Psykoud’Boul",
"Confusion" : "Choc Mental",
"Poison Sting" : "Dard-Venin",
"Bubble" : "Écume",
"Feint Attack" : "Feinte",
"Steel Wing" : "Aile d’Acier",
"Fire Fang" : "Crocs Feu",
"Rock Smash" : "Éclate-Roc",
"Transform" : "Morphing",
"Counter" : "Riposte",
"Powder Snow" : "Poudreuse",
"Close Combat" : "Close Combat",
"Dynamic Punch" : "Dynamopoing",
"Focus Blast" : "Exploforce",
"Aurora Beam" : "Onde Boréale",
"Charge Beam" : "Rayon Chargé",
"Volt Switch" : "Change Éclair",
"Wild Charge" : "Éclair Fou",
"Zap Cannon" : "Élecanon",
"Dragon Tail" : "Draco-Queue",
"Avalanche" : "Avalanche",
"Air Slash" : "Lame d’Air",
"Brave Bird" : "Rapace",
"Sky Attack" : "Piqué",
"Sand Tomb" : "Tourbi-Sable",
"Rock Blast" : "Boule Roc",
"Infestation" : "Harcèlement",
"Struggle Bug" : "Survinsecte",
"Silver Wind" : "Vent Argenté",
"Astonish" : "Étonnement",
"Hex" : "Châtiment",
"Night Shade" : "Ombre Nocturne",
"Iron Tail" : "Queue de Fer",
"Gyro Ball" : "Gyroballe",
"Heavy Slam" : "Tacle Lourd",
"Fire Spin" : "Danse Flamme",
"Overheat" : "Surchauffe",
"Bullet Seed" : "Balle Graine",
"Grass Knot" : "Nœud Herbe",
"Energy Ball" : "Éco-Sphère",
"Extrasensory" : "Extrasenseur",
"Future Sight" : "Prescience",
"Mirror Coat" : "Voile Miroir",
"Outrage" : "Colère",
"Snarl" : "Aboiement",
"Crunch" : "Mâchouille",
"Foul Play" : "Tricherie",
"Hidden Power" : "Puissance Cachée",
"Yawn" : "Bâillement",
"Take Down" : "Bélier",
"Draco Meteor" : "Draco Météore",
"Waterfall" : "Cascade",
"Surf" : "Surf",
"Psycho Boost" : "Psycho Boost",
"Doom Desire" : "Carnareket",
"Precipice Blades" : "Lame Pangéenne",
"Origin Pulse" : "Onde Originelle",
"Present" : "Cadeau",
"Weather Ball" : "Ball’Météo",
"Frenzy Plant" : "Végé-Attak",
"Blast Burn" : "Rafale Feu",
"Smack Down" : "Anti-Air",
"Hydro Cannon" : "Hydroblast",
"Last Resort" : "Dernier Recours"
}

new_moves = {}

for key, value in old_moves.iteritems():
	new_moves[key.upper()] = value


pokemons_src = {
"Bulbasaur" : "Bulbizarre",
"Ivysaur" : "Herbizarre",
"Venusaur" : "Florizarre",
"Charmander" : "Salamèche",
"Charmeleon" : "Reptincel",
"Charizard" : "Dracaufeu",
"Squirtle" : "Carapuce",
"Wartortle" : "Carabaffe",
"Blastoise" : "Tortank",
"Caterpie" : "Chenipan",
"Metapod" : "Chrysacier",
"Butterfree" : "Papilusion",
"Weedle" : "Aspicot",
"Kakuna" : "Coconfort",
"Beedrill" : "Dardargnan",
"Pidgey" : "Roucool",
"Pidgeotto" : "Roucoups",
"Pidgeot" : "Roucarnage",
"Rattata" : "Rattata",
"Raticate" : "Rattatac",
"Spearow" : "Piafabec",
"Fearow" : "Rapasdepic",
"Ekans" : "Abo",
"Arbok" : "Arbok",
"Pikachu" : "Pikachu",
"Raichu" : "Raichu",
"Sandshrew" : "Sabelette",
"Sandslash" : "Sablaireau",
"Nidoran♀" : "Nidoran♀",
"Nidorina" : "Nidorina",
"Nidoqueen" : "Nidoqueen",
"Nidoran♂" : "Nidoran♂",
"Nidorino" : "Nidorino",
"Nidoking" : "Nidoking",
"Clefairy" : "Mélofée",
"Clefable" : "Mélodelfe",
"Vulpix" : "Goupix",
"Ninetales" : "Feunard",
"Jigglypuff" : "Rondoudou",
"Wigglytuff" : "Grodoudou",
"Zubat" : "Nosferapti",
"Golbat" : "Nosferalto",
"Oddish" : "Mystherbe",
"Gloom" : "Ortide",
"Vileplume" : "Rafflesia",
"Paras" : "Paras",
"Parasect" : "Parasect",
"Venonat" : "Mimitoss",
"Venomoth" : "Aéromite",
"Diglett" : "Taupiqueur",
"Dugtrio" : "Triopikeur",
"Meowth" : "Miaouss",
"Persian" : "Persian",
"Psyduck" : "Psykokwak",
"Golduck" : "Akwakwak",
"Mankey" : "Férosinge",
"Primeape" : "Colossinge",
"Growlithe" : "Caninos",
"Arcanine" : "Arcanin",
"Poliwag" : "Ptitard",
"Poliwhirl" : "Têtarte",
"Poliwrath" : "Tartard",
"Abra" : "Abra",
"Kadabra" : "Kadabra",
"Alakazam" : "Alakazam",
"Machop" : "Machoc",
"Machoke" : "Machopeur",
"Machamp" : "Mackogneur",
"Bellsprout" : "Chétiflor",
"Weepinbell" : "Boustiflor",
"Victreebel" : "Empiflor",
"Tentacool" : "Tentacool",
"Tentacruel" : "Tentacruel",
"Geodude" : "Racaillou",
"Graveler" : "Gravalanch",
"Golem" : "Grolem",
"Ponyta" : "Ponyta",
"Rapidash" : "Galopa",
"Slowpoke" : "Ramoloss",
"Slowbro" : "Flagadoss",
"Magnemite" : "Magnéti",
"Magneton" : "Magnéton",
"Farfetch'd" : "Canarticho",
"Doduo" : "Doduo",
"Dodrio" : "Dodrio",
"Seel" : "Otaria",
"Dewgong" : "Lamantine",
"Grimer" : "Tadmorv",
"Muk" : "Grotadmorv",
"Shellder" : "Kokiyas",
"Cloyster" : "Crustabri",
"Gastly" : "Fantominus",
"Haunter" : "Spectrum",
"Gengar" : "Ectoplasma",
"Onix" : "Onix",
"Drowzee" : "Soporifik",
"Hypno" : "Hypnomade",
"Krabby" : "Krabby",
"Kingler" : "Krabboss",
"Voltorb" : "Voltorbe",
"Electrode" : "Électrode",
"Exeggcute" : "Noeunoeuf",
"Exeggutor" : "Noadkoko",
"Cubone" : "Osselait",
"Marowak" : "Ossatueur",
"Hitmonlee" : "Kicklee",
"Hitmonchan" : "Tygnon",
"Lickitung" : "Excelangue",
"Koffing" : "Smogo",
"Weezing" : "Smogogo",
"Rhyhorn" : "Rhinocorne",
"Rhydon" : "Rhinoféros",
"Chansey" : "Leveinard",
"Tangela" : "Saquedeneu",
"Kangaskhan" : "Kangourex",
"Horsea" : "Hypotrempe",
"Seadra" : "Hypocéan",
"Goldeen" : "Poissirène",
"Seaking" : "Poissoroy",
"Staryu" : "Stari",
"Starmie" : "Staross",
"Mr. Mime" : "M. Mime",
"Scyther" : "Insécateur",
"Jynx" : "Lippoutou",
"Electabuzz" : "Élektek",
"Magmar" : "Magmar",
"Pinsir" : "Scarabrute",
"Tauros" : "Tauros",
"Magikarp" : "Magicarpe",
"Gyarados" : "Léviator",
"Lapras" : "Lokhlass",
"Ditto" : "Métamorph",
"Eevee" : "Évoli",
"Vaporeon" : "Aquali",
"Jolteon" : "Voltali",
"Flareon" : "Pyroli",
"Porygon" : "Porygon",
"Omanyte" : "Amonita",
"Omastar" : "Amonistar",
"Kabuto" : "Kabuto",
"Kabutops" : "Kabutops",
"Aerodactyl" : "Ptéra",
"Snorlax" : "Ronflex",
"Articuno" : "Artikodin",
"Zapdos" : "Électhor",
"Moltres" : "Sulfura",
"Dratini" : "Minidraco",
"Dragonair" : "Draco",
"Dragonite" : "Dracolosse",
"Mewtwo" : "Mewtwo",
"Mew" : "Mew",
"Chikorita" : "Germignon",
"Bayleef" : "Macronium",
"Meganium" : "Méganium",
"Cyndaquil" : "Héricendre",
"Quilava" : "Feurisson",
"Typhlosion" : "Typhlosion",
"Totodile" : "Kaiminus",
"Croconaw" : "Crocrodil",
"Feraligatr" : "Aligatueur",
"Sentret" : "Fouinette",
"Furret" : "Fouinar",
"Hoothoot" : "Hoothoot",
"Noctowl" : "Noarfang",
"Ledyba" : "Coxy",
"Ledian" : "Coxyclaque",
"Spinarak" : "Mimigal",
"Ariados" : "Migalos",
"Crobat" : "Nostenfer",
"Chinchou" : "Loupio",
"Lanturn" : "Lanturn",
"Pichu" : "Pichu",
"Cleffa" : "Mélo",
"Igglybuff" : "Toudoudou",
"Togepi" : "Togepi",
"Togetic" : "Togetic",
"Natu" : "Natu",
"Xatu" : "Xatu",
"Mareep" : "Wattouat",
"Flaaffy" : "Lainergie",
"Ampharos" : "Pharamp",
"Bellossom" : "Joliflor",
"Marill" : "Marill",
"Azumarill" : "Azumarill",
"Sudowoodo" : "Simularbre",
"Politoed" : "Tarpaud",
"Hoppip" : "Granivol",
"Skiploom" : "Floravol",
"Jumpluff" : "Cotovol",
"Aipom" : "Capumain",
"Sunkern" : "Tournegrin",
"Sunflora" : "Héliatronc",
"Yanma" : "Yanma",
"Wooper" : "Axoloto",
"Quagsire" : "Maraiste",
"Espeon" : "Mentali",
"Umbreon" : "Noctali",
"Murkrow" : "Cornèbre",
"Slowking" : "Roigada",
"Misdreavus" : "Feuforêve",
"Unown" : "Zarbi",
"Wobbuffet" : "Qulbutoké",
"Girafarig" : "Girafarig",
"Pineco" : "Pomdepik",
"Forretress" : "Foretress",
"Dunsparce" : "Insolourdo",
"Gligar" : "Scorplane",
"Steelix" : "Steelix",
"Snubbull" : "Snubbull",
"Granbull" : "Granbull",
"Qwilfish" : "Qwilfish",
"Scizor" : "Cizayox",
"Shuckle" : "Caratroc",
"Heracross" : "Scarhino",
"Sneasel" : "Farfuret",
"Teddiursa" : "Teddiursa",
"Ursaring" : "Ursaring",
"Slugma" : "Limagma",
"Magcargo" : "Volcaropod",
"Swinub" : "Marcacrin",
"Piloswine" : "Cochignon",
"Corsola" : "Corayon",
"Remoraid" : "Rémoraid",
"Octillery" : "Octillery",
"Delibird" : "Cadoizo",
"Mantine" : "Démanta",
"Skarmory" : "Airmure",
"Houndour" : "Malosse",
"Houndoom" : "Démolosse",
"Kingdra" : "Hyporoi",
"Phanpy" : "Phanpy",
"Donphan" : "Donphan",
"Porygon2" : "Porygon2",
"Stantler" : "Cerfrousse",
"Smeargle" : "Queulorior",
"Tyrogue" : "Debugant",
"Hitmontop" : "Kapoera",
"Smoochum" : "Lippouti",
"Elekid" : "Élekid",
"Magby" : "Magby",
"Miltank" : "Écrémeuh",
"Blissey" : "Leuphorie",
"Raikou" : "Raikou",
"Entei" : "Entei",
"Suicune" : "Suicune",
"Larvitar" : "Embrylex",
"Pupitar" : "Ymphect",
"Tyranitar" : "Tyranocif",
"Lugia" : "Lugia",
"Ho-Oh" : "Ho-Oh",
"Celebi" : "Celebi",
"Treecko" : "Arcko",
"Grovyle" : "Massko",
"Sceptile" : "Jungko",
"Torchic" : "Poussifeu",
"Combusken" : "Galifeu",
"Blaziken" : "Braségali",
"Mudkip" : "Gobou",
"Marshtomp" : "Flobio",
"Swampert" : "Laggron",
"Poochyena" : "Medhyèna",
"Mightyena" : "Grahyèna",
"Zigzagoon" : "Zigzaton",
"Linoone" : "Linéon",
"Wurmple" : "Chenipotte",
"Silcoon" : "Armulys",
"Beautifly" : "Charmillon",
"Cascoon" : "Blindalys",
"Dustox" : "Papinox",
"Lotad" : "Nénupiot",
"Lombre" : "Lombre",
"Ludicolo" : "Ludicolo",
"Seedot" : "Grainipiot",
"Nuzleaf" : "Pifeuil",
"Shiftry" : "Tengalice",
"Taillow" : "Nirondelle",
"Swellow" : "Hélédelle",
"Wingull" : "Goélise",
"Pelipper" : "Bekipan",
"Ralts" : "Tarsal",
"Kirlia" : "Kirlia",
"Gardevoir" : "Gardevoir",
"Surskit" : "Arakdo",
"Masquerain" : "Maskadra",
"Shroomish" : "Balignon",
"Breloom" : "Chapignon",
"Slakoth" : "Parecool",
"Vigoroth" : "Vigoroth",
"Slaking" : "Monaflèmit",
"Nincada" : "Ningale",
"Ninjask" : "Ninjask",
"Shedinja" : "Munja",
"Whismur" : "Chuchmur",
"Loudred" : "Ramboum",
"Exploud" : "Brouhabam",
"Makuhita" : "Makuhita",
"Hariyama" : "Hariyama",
"Azurill" : "Azurill",
"Nosepass" : "Tarinor",
"Skitty" : "Skitty",
"Delcatty" : "Delcatty",
"Sableye" : "Ténéfix",
"Mawile" : "Mysdibule",
"Aron" : "Galekid",
"Lairon" : "Galegon",
"Aggron" : "Galeking",
"Meditite" : "Méditikka",
"Medicham" : "Charmina",
"Electrike" : "Dynavolt",
"Manectric" : "Élecsprint",
"Plusle" : "Posipi",
"Minun" : "Négapi",
"Volbeat" : "Muciole",
"Illumise" : "Lumivole",
"Roselia" : "Rosélia",
"Gulpin" : "Gloupti",
"Swalot" : "Avaltout",
"Carvanha" : "Carvanha",
"Sharpedo" : "Sharpedo",
"Wailmer" : "Wailmer",
"Wailord" : "Wailord",
"Numel" : "Chamallot",
"Camerupt" : "Camérupt",
"Torkoal" : "Chartor",
"Spoink" : "Spoink",
"Grumpig" : "Groret",
"Spinda" : "Spinda",
"Trapinch" : "Kraknoix",
"Vibrava" : "Vibraninf",
"Flygon" : "Libégon",
"Cacnea" : "Cacnea",
"Cacturne" : "Cacturne",
"Swablu" : "Tylton",
"Altaria" : "Altaria",
"Zangoose" : "Mangriff",
"Seviper" : "Séviper",
"Lunatone" : "Séléroc",
"Solrock" : "Solaroc",
"Barboach" : "Barloche",
"Whiscash" : "Barbicha",
"Corphish" : "Écrapince",
"Crawdaunt" : "Colhomard",
"Baltoy" : "Balbuto",
"Claydol" : "Kaorine",
"Lileep" : "Lilia",
"Cradily" : "Vacilys",
"Anorith" : "Anorith",
"Armaldo" : "Armaldo",
"Feebas" : "Barpau",
"Milotic" : "Milobellus",
"Castform" : "Morphéo",
"Kecleon" : "Kecleon",
"Shuppet" : "Polichombr",
"Banette" : "Branette",
"Duskull" : "Skelénox",
"Dusclops" : "Téraclope",
"Tropius" : "Tropius",
"Chimecho" : "Éoko",
"Absol" : "Absol",
"Wynaut" : "Okéoké",
"Snorunt" : "Stalgamin",
"Glalie" : "Oniglali",
"Spheal" : "Obalie",
"Sealeo" : "Phogleur",
"Walrein" : "Kaimorse",
"Clamperl" : "Coquiperl",
"Huntail" : "Serpang",
"Gorebyss" : "Rosabyss",
"Relicanth" : "Relicanth",
"Luvdisc" : "Lovdisc",
"Bagon" : "Draby",
"Shelgon" : "Drackhaus",
"Salamence" : "Drattak",
"Beldum" : "Terhal",
"Metang" : "Métang",
"Metagross" : "Métalosse",
"Regirock" : "Regirock",
"Regice" : "Regice",
"Registeel" : "Registeel",
"Latias" : "Latias",
"Latios" : "Latios",
"Kyogre" : "Kyogre",
"Groudon" : "Groudon",
"Rayquaza" : "Rayquaza",
"Jirachi" : "Jirachi",
"Deoxys" : "Deoxys"
}

pokemons = {}
for key, value in pokemons_src.iteritems():
	pokemons[key.upper()] = value


ALOLA = {
          "RATTATA_ALOLA" : "Rattata d'alola",
          "RATICATE_ALOLA" : "Rattatac d'alola",
          "RAICHU_ALOLA" : "Raichu d'alola",
          "SANDSHREW_ALOLA" : "Sabelette d'alola",
          "SANDSLASH_ALOLA" : "Sablaireau d'alola",
          "VULPIX_ALOLA" : "Goupix d'alola",
          "NINETALES_ALOLA" : "Feunard d'alola",
          "DIGLETT_ALOLA" : "Taupiqueur d'alola",
          "DUGTRIO_ALOLA" : "Triopiqueur d'alola",
          "MEOWTH_ALOLA" : "Miaouss d'alola",
          "PERSIAN_ALOLA" : "Persian d'alola",
          "GEODUDE_ALOLA" : "Racaillou d'alola",
          "GRAVELER_ALOLA" : "Gravalanche d'alola",
          "GOLEM_ALOLA" : "Grolem d'alola",
          "GRIMER_ALOLA" : "Tadmorv d'alola",
          "MUK_ALOLA" : "Grotadmorv d'alola",
          "EXEGGUTOR_ALOLA" : "Nœunœuf d'alola",
          "MAROWAK_ALOLA": "Ossatueur d'alola"
}

for key, value in ALOLA.iteritems():
	pokemons[key] = value


pokemons_reverse_id = {}
for key, value in pokemons.iteritems():
	pokemons_reverse_id[value] = key

ID_TYPES = {
    "plante": "POKEMON_TYPE_GRASS",
	"roche": "POKEMON_TYPE_ROCK",
	"glace": "POKEMON_TYPE_ICE",
	"dragon": "POKEMON_TYPE_DRAGON",
	"tenebre": "POKEMON_TYPE_DARK",
	"psy": "POKEMON_TYPE_PSYCHIC",
	"insecte": "POKEMON_TYPE_BUG",
	"vol": "POKEMON_TYPE_FLYING",
	"acier": "POKEMON_TYPE_STEEL",
	"feu": "POKEMON_TYPE_FIRE",
	"combat": "POKEMON_TYPE_FIGHTING",
	"sol": "POKEMON_TYPE_GROUND",
	"spectre": "POKEMON_TYPE_GHOST",
	"poison": "POKEMON_TYPE_POISON",
	"eau": "POKEMON_TYPE_WATER",
	"fee": "POKEMON_TYPE_FAIRY",
	"electrique": "POKEMON_TYPE_ELECTRIC",
	"normal": "POKEMON_TYPE_NORMAL"
}

types = {}
for key, value in ID_TYPES.iteritems():
	types[value] = key

sentences = {}
sentences["show_info"] = ["mode info", "info", "forces", "force"]
sentences["show_fight"] = ["mode combat", "combat", "passe en mode combat", "mets le mode combat", "faiblesses", "donne les faiblesses"]
sentences["state"] = "Je suis en mode "
sentences["state_info"] = "info"
sentences["state_fight"] = "combat"
sentences["forces"] = "{0} est un pokemon de type {1}. Il est fort contre les types "
sentences["weaknesses"] = "{0} est faible contre les types "

french_json = {}
french_json["pokemons"] = pokemons
french_json["pokemons_reverse_id"] = pokemons_reverse_id
french_json["moves"] = new_moves
french_json["types"] = types
french_json["sentences"] = sentences

with open('../Pokedviser/txt_french.json', 'w') as outfile:
    json.dump(french_json, outfile, sort_keys = True, indent = 4,
               ensure_ascii = False)

